//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Pupils = new HashSet<Pupil>();
            this.PostalAddress = new Address();
        }
    
        public int Id { get; set; }
        public string SchoolName { get; set; }
    
        public Address PostalAddress { get; set; }
    
        public virtual ICollection<Pupil> Pupils { get; set; }
    }
}
