//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise06_ClientUsingWsdl.ExerciseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://www.firebrandtraining.com/exercise06/2016/05/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExerciseServiceReference.IExercise")]
    public interface IExercise {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExercise/GetTotalNumberOfChars", ReplyAction="http://tempuri.org/IExercise/GetTotalNumberOfCharsResponse")]
        int GetTotalNumberOfChars(string[] arrayOfStrings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExercise/GetTotalNumberOfChars", ReplyAction="http://tempuri.org/IExercise/GetTotalNumberOfCharsResponse")]
        System.Threading.Tasks.Task<int> GetTotalNumberOfCharsAsync(string[] arrayOfStrings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExercise/Factorial", ReplyAction="http://tempuri.org/IExercise/FactorialResponse")]
        int Factorial(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExercise/Factorial", ReplyAction="http://tempuri.org/IExercise/FactorialResponse")]
        System.Threading.Tasks.Task<int> FactorialAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExercise/HowManyDaysOld", ReplyAction="http://tempuri.org/IExercise/HowManyDaysOldResponse")]
        string HowManyDaysOld(Exercise06_ClientUsingWsdl.ExerciseServiceReference.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExercise/HowManyDaysOld", ReplyAction="http://tempuri.org/IExercise/HowManyDaysOldResponse")]
        System.Threading.Tasks.Task<string> HowManyDaysOldAsync(Exercise06_ClientUsingWsdl.ExerciseServiceReference.Person person);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExerciseChannel : Exercise06_ClientUsingWsdl.ExerciseServiceReference.IExercise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExerciseClient : System.ServiceModel.ClientBase<Exercise06_ClientUsingWsdl.ExerciseServiceReference.IExercise>, Exercise06_ClientUsingWsdl.ExerciseServiceReference.IExercise {
        
        public ExerciseClient() {
        }
        
        public ExerciseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExerciseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExerciseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExerciseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetTotalNumberOfChars(string[] arrayOfStrings) {
            return base.Channel.GetTotalNumberOfChars(arrayOfStrings);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalNumberOfCharsAsync(string[] arrayOfStrings) {
            return base.Channel.GetTotalNumberOfCharsAsync(arrayOfStrings);
        }
        
        public int Factorial(int number) {
            return base.Channel.Factorial(number);
        }
        
        public System.Threading.Tasks.Task<int> FactorialAsync(int number) {
            return base.Channel.FactorialAsync(number);
        }
        
        public string HowManyDaysOld(Exercise06_ClientUsingWsdl.ExerciseServiceReference.Person person) {
            return base.Channel.HowManyDaysOld(person);
        }
        
        public System.Threading.Tasks.Task<string> HowManyDaysOldAsync(Exercise06_ClientUsingWsdl.ExerciseServiceReference.Person person) {
            return base.Channel.HowManyDaysOldAsync(person);
        }
    }
}
